# Generated by Django 3.2.4 on 2021-09-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
